Repository sofastack/sofa-common-tools, pull requests merged in 2020-11, with the labels that each got.

#92 Refactor using of sofa-common-tools and support for console logging
  core/src/main/java/com/alipay/sofa/common/log/CommonLoggingConfigurations.java
  core/src/main/java/com/alipay/sofa/common/log/env/LogEnvUtils.java
  core/src/main/java/com/alipay/sofa/common/log/factory/AbstractLoggerSpaceFactoryBuilder.java
  core/src/main/java/com/alipay/sofa/common/log/factory/Log4j2LoggerSpaceFactory.java
  core/src/main/java/com/alipay/sofa/common/log/factory/LogbackLoggerSpaceFactory.java
  core/src/main/java/com/alipay/sofa/common/log/spi/Log4j2FilterGenerator.java
  core/src/main/java/com/alipay/sofa/common/log/spi/Log4j2ReInitializer.java
  core/src/main/java/com/alipay/sofa/common/log/spi/LogbackFilterGenerator.java
  core/src/main/java/com/alipay/sofa/common/log/spi/LogbackReInitializer.java
  core/src/main/java/com/alipay/sofa/common/log/spi/ReInitializeChecker.java
  log-sofa-boot-starter/pom.xml
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/CommonLoggingApplicationListener.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/DefaultReInitializerChecker.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/Mark.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/filter/DefaultLog4j2FilterGenerator.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/filter/DefaultLogbackFilterGenerator.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/initializer/DefaultLog4j2ReInitializer.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/initializer/DefaultLogbackReInitializer.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/log4j2/SOFAConfigurationFactory.java
  log-sofa-boot-starter/src/main/java/com/alipay/sofa/common/boot/logging/util/SystemPropertiesGetter.java
  log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.Log4j2FilterGenerator
  log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.Log4j2ReInitializer
  log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.LogbackFilterGenerator
  log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.LogbackReInitializer
  log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.ReInitializeChecker
  log-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/BaseLogIntegrationTest.java
  log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/Log4j2IntegrationTest.java
  log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/LogbackIntegrationTest.java
  log-sofa-boot-starter/src/test/resources/logback-test-conf.xml
  log-sofa-boot-starter/src/test/resources/test/space/log/log4j2/log-conf.xml
  log-sofa-boot-starter/src/test/resources/test/space/log/logback/log-conf.xml
  pom.xml
Labels: cla:yes, size/XXL

#91 refactor the thread module
  core/src/main/java/com/alipay/sofa/common/thread/ExecutingRunnable.java
  core/src/main/java/com/alipay/sofa/common/thread/NamedThreadFactory.java
  core/src/main/java/com/alipay/sofa/common/thread/RunnableExecutionInfo.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolConstants.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolConfig.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolGovernor.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolMonitorRunner.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolMonitorWrapper.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolStatistics.java
  core/src/main/java/com/alipay/sofa/common/thread/TimeWaitRejectedExecutionHandler.java
  core/src/main/java/com/alipay/sofa/common/utils/TracerUtil.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolGovernorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolTestBase.java
Labels: cla:yes, size/XXL

#94 support monitor InQueueTime and RunningTime
  core/src/main/java/com/alipay/sofa/common/thread/ExecutingRunnable.java
  core/src/main/java/com/alipay/sofa/common/thread/RunnableExecutionInfo.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolMonitorRunner.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolStatistics.java
  core/src/main/java/com/alipay/sofa/common/thread/TimeWaitRejectedExecutionHandler.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskSchedulerTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolStaticsTest.java
Labels: cla:yes, size/L

#95 Fix thread test unit
  core/src/test/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/TimeWaitRejectedExecutionHandlerTest.java
Labels: cla:yes, size/S

#96 support namespace governor
  core/src/main/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolConfig.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolGovernor.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolMonitorWrapper.java
  core/src/main/java/com/alipay/sofa/common/thread/namespace/NamespaceNamedThreadFactory.java
  core/src/main/java/com/alipay/sofa/common/thread/namespace/ThreadPoolNamespace.java
  core/src/test/java/com/alipay/sofa/common/thread/NamespaceGovernorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/NamespaceNamedFactoryTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolGovernorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolTestBase.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaScheduledTreadPoolExecutorConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolExecutorConstructsTest.java
Labels: cla:yes, size/XL

#97 use SPI to find traceId
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolMonitorRunner.java
  core/src/main/java/com/alipay/sofa/common/tracer/TracerIdAdapter.java
  core/src/main/java/com/alipay/sofa/common/tracer/TracerIdRetriever.java
  core/src/main/java/com/alipay/sofa/common/utils/TracerUtil.java
  core/src/test/java/com/alipay/sofa/common/thread/NamespaceNamedFactoryTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskSchedulerTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolStaticsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolTestBase.java
  core/src/test/java/com/alipay/sofa/common/thread/TimeWaitRejectedExecutionHandlerTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaScheduledTreadPoolExecutorConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolExecutorConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolTaskExecutorConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolTaskSchedulerConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/tracer/SampleTracerIdRetriever.java
  core/src/test/java/com/alipay/sofa/common/tracer/TracerIdAdapterTest.java
  core/src/test/resources/META-INF/services/com.alipay.sofa.common.tracer.TracerIdRetriever
Labels: cla:yes, size/L

#98 let global log switch used by ThreadPoolMonitorRunner
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolConstants.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolGovernor.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolMonitorRunner.java
Labels: cla:yes, size/M

#99 rename scheduler
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolGovernor.java
Labels: cla:yes, size/XS

#100 Reset average statics after each monitor
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolMonitorRunner.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolStatistics.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskSchedulerTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolStaticsTest.java
Labels: cla:yes, size/M

#101 rename namespace to space
  core/src/main/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskExecutor.java
  core/src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolTaskScheduler.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolConfig.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolGovernor.java
  core/src/main/java/com/alipay/sofa/common/thread/space/SpaceNamedThreadFactory.java
  core/src/main/java/com/alipay/sofa/common/thread/space/ThreadPoolSpace.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SpaceGovernorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/SpaceNamedFactoryTest.java
  core/src/test/java/com/alipay/sofa/common/thread/ThreadPoolGovernorTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaScheduledTreadPoolExecutorConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolExecutorConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolTaskExecutorConstructsTest.java
  core/src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolTaskSchedulerConstructsTest.java
  core/src/test/resources/thread/sofaThreadPoolTaskExecutor.xml
  core/src/test/resources/thread/sofaThreadPoolTaskScheduler.xml
Labels: cla:yes, size/L

#102 Fix compatibilty for sofaboot 3.4.5 and previous verison
  core/src/main/java/com/alipay/sofa/common/log/env/LogEnvUtils.java
  core/src/main/java/com/alipay/sofa/common/log/factory/Log4j2LoggerSpaceFactory.java
  core/src/main/java/com/alipay/sofa/common/log/factory/LogbackLoggerSpaceFactory.java
  core/src/main/java/com/alipay/sofa/common/log/spi/Log4j2ReInitializer.java
  core/src/main/java/com/alipay/sofa/common/log/spi/LogbackReInitializer.java
  core/src/main/java/com/alipay/sofa/common/log/spi/ReInitializeChecker.java
Labels: bug, cla:yes, size/L
