Repository sofastack/sofa-common-tools, pull requests merged in 2020-12, with the labels that each got.

#105 Create ci.yml
  .github/workflows/ci.yml
  README.md
Labels: cla:yes, size/S

#106 refactor thread-pool space
  core/src/main/java/com/alipay/sofa/common/space/Space.java
  core/src/main/java/com/alipay/sofa/common/thread/ThreadPoolGovernor.java
  core/src/main/java/com/alipay/sofa/common/thread/space/ThreadPoolSpace.java
Labels: cla:yes, size/M

#107 Support code2description feature
  core/src/main/java/com/alipay/sofa/common/code/LogCode2Description.java
  core/src/main/java/com/alipay/sofa/common/log/MultiAppLoggerSpaceManager.java
  core/src/main/java/com/alipay/sofa/common/space/Space.java
  core/src/main/java/com/alipay/sofa/common/space/SpaceId.java
  core/src/main/java/com/alipay/sofa/common/utils/ReportUtil.java
  core/src/test/java/com/alipay/sofa/common/log/code/LogCode2DescriptionTest.java
  core/src/test/resources/SOFA-TEST/log-codes.properties
  core/src/test/resources/SOFA-TEST/log-codes_zh_CN.properties
Labels: cla:yes, size/L

#89 common config poc
  core/src/main/java/com/alipay/sofa/common/CommonToolConfigKeys.java
  core/src/main/java/com/alipay/sofa/common/config/ConfigKey.java
  core/src/main/java/com/alipay/sofa/common/config/ConfigManager.java
  core/src/main/java/com/alipay/sofa/common/config/ConfigSource.java
  core/src/main/java/com/alipay/sofa/common/config/Converter.java
  core/src/main/java/com/alipay/sofa/common/config/DefaultConfigManger.java
  core/src/main/java/com/alipay/sofa/common/config/ManagementListener.java
  core/src/main/java/com/alipay/sofa/common/config/SofaConfigs.java
  core/src/main/java/com/alipay/sofa/common/config/converter/DefaultConverter.java
  core/src/main/java/com/alipay/sofa/common/config/converter/GlobalConverterHolder.java
  core/src/main/java/com/alipay/sofa/common/config/listener/AbstractConfigListener.java
  core/src/main/java/com/alipay/sofa/common/config/listener/LogConfigListener.java
  core/src/main/java/com/alipay/sofa/common/config/log/ConfigLoggerFactory.java
  core/src/main/java/com/alipay/sofa/common/config/source/AbstractConfigSource.java
  core/src/main/java/com/alipay/sofa/common/config/source/ConfigSourceOrder.java
  core/src/main/java/com/alipay/sofa/common/config/source/SystemEnvConfigSource.java
  core/src/main/java/com/alipay/sofa/common/config/source/SystemPropertyConfigSource.java
  core/src/main/java/com/alipay/sofa/common/utils/OrderComparator.java
  core/src/main/java/com/alipay/sofa/common/utils/Ordered.java
  core/src/main/resources/com/alipay/sofa/common/config/log4j/log-conf.xml
  core/src/main/resources/com/alipay/sofa/common/config/log4j2/log-conf.xml
  core/src/main/resources/com/alipay/sofa/common/config/logback/log-conf.xml
  core/src/test/java/com/alipay/sofa/common/config/CommonConfigTest.java
  core/src/test/java/com/alipay/sofa/common/config/ConfigKeyTest.java
  core/src/test/java/com/alipay/sofa/common/config/ConfigLoggerFactoryTest.java
  core/src/test/java/com/alipay/sofa/common/config/ConfigSourceTest.java
  core/src/test/java/com/alipay/sofa/common/config/DefaultConverterTest.java
Labels: cla:yes, size/XXL

#109 rename spaces
  core/src/main/java/com/alipay/sofa/common/config/log/ConfigLoggerFactory.java
  core/src/main/java/com/alipay/sofa/common/utils/ThreadLoggerFactory.java
  core/src/main/resources/sofa-common-tools/log/log4j/log-conf.xml
  core/src/main/resources/sofa-common-tools/log/log4j2/log-conf.xml
  core/src/main/resources/sofa-common-tools/log/logback/log-conf.xml
  core/src/main/resources/sofa-thread/log/log4j/log-conf.xml
  core/src/main/resources/sofa-thread/log/log4j2/log-conf.xml
  core/src/main/resources/sofa-thread/log/logback/log-conf.xml
Labels: cla:yes, size/XS

#111 fix common config unit test
  core/src/test/java/com/alipay/sofa/common/config/CommonConfigTest.java
Labels: bug, cla:yes, size/XS

#112 Remove pom.xml and optimize surefire config
  core/src/main/java/com/alipay/sofa/common/space/Space.java
  pom.xml
Labels: cla:yes, size/M

#113 Fix compatibility for old SpaceId
  core/src/main/java/com/alipay/sofa/common/log/LoggerSpaceManager.java
  core/src/main/java/com/alipay/sofa/common/log/MultiAppLoggerSpaceManager.java
  core/src/main/java/com/alipay/sofa/common/log/SpaceId.java
  pom.xml
Labels: bug, cla:yes, size/M

#114 fix logger multiple initialize problem
  core/src/main/java/com/alipay/sofa/common/log/LoggerSpaceManager.java
Labels: bug, cla:yes, size/XS

#115 Add more specific information.
  core/src/main/java/com/alipay/sofa/common/log/MultiAppLoggerSpaceManager.java
Labels: cla:yes

#116 Remove log console set logger level
  core/src/main/java/com/alipay/sofa/common/log/factory/Log4j2LoggerSpaceFactory.java
  core/src/main/java/com/alipay/sofa/common/log/factory/LogbackLoggerSpaceFactory.java
Labels: cla:yes, size/M

#117 Remove space id instead of setting null
  core/src/main/java/com/alipay/sofa/common/log/MultiAppLoggerSpaceManager.java
Labels: cla:yes, size/XS

#118 Defaults to no console logging
  core/src/main/java/com/alipay/sofa/common/log/CommonLoggingConfigurations.java
Labels: cla:yes, size/XS

#121 Fix log-conf.xml
  core/src/main/java/com/alipay/sofa/common/config/log/ConfigLoggerFactory.java
  core/src/main/resources/sofa-common-tools/log/log4j/log-conf.xml
  core/src/main/resources/sofa-common-tools/log/log4j2/log-conf.xml
  core/src/main/resources/sofa-common-tools/log/logback/log-conf.xml
  core/src/main/resources/sofa-thread/log/log4j/log-conf.xml
  core/src/main/resources/sofa-thread/log/log4j2/log-conf.xml
  core/src/main/resources/sofa-thread/log/logback/log-conf.xml
Labels: bug, cla:yes, size/S

#123 Fix compatibility on old version of SOFABoot
  src/main/java/com/alipay/sofa/common/log/MultiAppLoggerSpaceManager.java
Labels: bug, cla:yes, size/XS

#124 Not override threadFactory when construct has threadFactory param
  src/main/java/com/alipay/sofa/common/thread/SofaScheduledThreadPoolExecutor.java
  src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutor.java
  src/test/java/com/alipay/sofa/common/thread/SpaceNamedFactoryTest.java
  src/test/java/com/alipay/sofa/common/thread/construct/SofaScheduledTreadPoolExecutorConstructsTest.java
  src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolExecutorConstructsTest.java
Labels: cla:yes, question, size/M

#125 Release 1.3.0
  pom.xml
  src/test/java/com/alipay/sofa/common/thread/construct/SofaScheduledTreadPoolExecutorConstructsTest.java
  src/test/java/com/alipay/sofa/common/thread/construct/SofaThreadPoolExecutorConstructsTest.java
Labels: cla:yes, size/XS

#127 Update version to 1.3.1-SNAPSHOT
  pom.xml
Labels: cla:yes, size/XS

#129 Revert "Refine log4j 1 judgement logic"
  src/main/java/com/alipay/sofa/common/log/env/LogEnvUtils.java
Labels: cla:yes, size/XS

#128 Add deprecated methods in SofaThreadPoolExecutor
  src/main/java/com/alipay/sofa/common/thread/SofaThreadPoolExecutor.java
Labels: cla:yes, size/M

#130 add commons-logging build
  src/main/java/com/alipay/sofa/common/log/Constants.java
  src/main/java/com/alipay/sofa/common/log/MultiAppLoggerSpaceManager.java
  src/main/java/com/alipay/sofa/common/log/factory/LoggerSpaceFactory4CommonsLoggingBuilder.java
Labels: cla:yes, size/S

#131 Release 1.3.1
  pom.xml
Labels: cla:yes, size/XS
