Repository sofastack/sofa-common-tools, pull requests merged in 2020-03, with the labels that each got.

#59 upgrade to 1.0.22-SNAPSHOT
  core/pom.xml
  log-sofa-boot-starter/pom.xml
  pom.xml
Labels: First-time contributor, cla:yes, size/XS

#60 fix-multiapploggerspanemanager
  core/src/main/java/com/alipay/sofa/common/log/MultiAppLoggerSpaceManager.java
Labels: First-time contributor, bug, cla:yes, size/S

#63 upgrade version to 1.0.22
  core/pom.xml
  log-sofa-boot-starter/pom.xml
  pom.xml
Labels: cla:yes, size/XS

#65 Fix ci.
  .travis.yml
  README.md
Labels: bug, cla:yes, size/XS
