Repository sofastack/sofa-common-tools, pull requests merged in 2021-09, with the labels that each got.

#149 Update version to 1.3.7-SNAPSHOT.
  pom.xml
Labels: cla:yes, size/XS

#148 level evel 等级 应为info 原先为into
  src/main/resources/sofa-common-tools/log/log4j/log-conf.xml
Labels: First-time contributor, cla:yes, size/XS

#150 fix ConfigManager concurrent problem
  src/main/java/com/alipay/sofa/common/config/DefaultConfigManger.java
Labels: bug, cla:yes, size/XS
